services:
    sylius.shop.menu_builder.account:
        class: App\Menu\AccountMenuBuilder
        arguments: ['@knp_menu.factory', '@event_dispatcher']
        tags:
            - {name: knp_menu.menu_builder, method: createMenu, alias: sylius.shop.account }
    
    sylius.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addRefundMenu }
