imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusPayPalPlugin/Resources/config/config.yaml" }
    
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/config.yml" }
    - { resource: "@OdiseoSyliusBlogPlugin/Resources/config/config.yaml" }
    - { resource: "@OdiseoSyliusVendorPlugin/Resources/config/config.yaml" }
    - { resource: "@BitBagSyliusElasticsearchPlugin/Resources/config/config.yml" }
parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_addressing:
    resources:
        address:
            classes:
                model: App\Entity\Addressing\Address
        country:
            classes:
                model: App\Entity\Addressing\Country
        province:
            classes:
                model: App\Entity\Addressing\Province
        zone:
            classes:
                model: App\Entity\Addressing\Zone
        zone_member:
            classes:
                model: App\Entity\Addressing\ZoneMember

sylius_admin_api:
    resources:
        api_client:
            classes:
                model: App\Entity\AdminApi\Client
        api_access_token:
            classes:
                model: App\Entity\AdminApi\AccessToken
        api_refresh_token:
            classes:
                model: App\Entity\AdminApi\RefreshToken
        api_auth_code:
            classes:
                model: App\Entity\AdminApi\AuthCode

sylius_attribute:
    resources:
        product:
            attribute:
                classes:
                    model: App\Entity\Product\ProductAttribute
                translation:
                    classes:
                        model: App\Entity\Product\ProductAttributeTranslation
            attribute_value:
                classes:
                    model: App\Entity\Product\ProductAttributeValue

sylius_channel:
    resources:
        channel:
            classes:
                model: App\Entity\Channel\Channel
sylius_core:
    resources:
        product_image:
            classes:
                model: App\Entity\Product\ProductImage
        taxon_image:
            classes:
                model: App\Entity\Taxonomy\TaxonImage
        product_taxon:
            classes:
                model: App\Entity\Product\ProductTaxon
        channel_pricing:
            classes:
                model: App\Entity\Channel\ChannelPricing

sylius_currency:
    resources:
        currency:
            classes:
                model: App\Entity\Currency\Currency
        exchange_rate:
            classes:
                model: App\Entity\Currency\ExchangeRate

sylius_customer:
    resources:
        customer:
            classes:
                model: App\Entity\Customer\Customer
        customer_group:
            classes:
                model: App\Entity\Customer\CustomerGroup

sylius_locale:
    resources:
        locale:
            classes:
                model: App\Entity\Locale\Locale

sylius_order:
    resources:
        order:
            classes:
                model: App\Entity\Order\Order
                controller: App\Controller\OrderController
        order_item:
            classes:
                model: App\Entity\Order\OrderItem
        order_item_unit:
            classes:
                model: App\Entity\Order\OrderItemUnit
        adjustment:
            classes:
                model: App\Entity\Order\Adjustment
        order_sequence:
            classes:
                model: App\Entity\Order\OrderSequence

sylius_payment:
    resources:
        payment_method:
            classes:
                model: App\Entity\Payment\PaymentMethod
            translation:
                classes:
                    model: App\Entity\Payment\PaymentMethodTranslation
        payment:
            classes:
                model: App\Entity\Payment\Payment

sylius_payum:
    resources:
        payment_security_token:
            classes:
                model: App\Entity\Payment\PaymentSecurityToken
        gateway_config:
            classes:
                model: App\Entity\Payment\GatewayConfig

sylius_product:
    resources:
        product:
            classes:
                repository: App\Repository\ProductRepository
                model: App\Entity\Product\Product
            translation:
                classes:
                    model: App\Entity\Product\ProductTranslation
        product_variant:
            classes:
                model: App\Entity\Product\ProductVariant
            translation:
                classes:
                    model: App\Entity\Product\ProductVariantTranslation
        product_option:
            classes:
                model: App\Entity\Product\ProductOption
            translation:
                classes:
                    model: App\Entity\Product\ProductOptionTranslation
        product_option_value:
            classes:
                model: App\Entity\Product\ProductOptionValue
            translation:
                classes:
                    model: App\Entity\Product\ProductOptionValueTranslation
        product_association:
            classes:
                model: App\Entity\Product\ProductAssociation
        product_association_type:
            classes:
                model: App\Entity\Product\ProductAssociationType
            translation:
                classes:
                    model: App\Entity\Product\ProductAssociationTypeTranslation

sylius_promotion:
    resources:
        promotion:
            classes:
                model: App\Entity\Promotion\Promotion
        promotion_rule:
            classes:
                model: App\Entity\Promotion\PromotionRule
        promotion_action:
            classes:
                model: App\Entity\Promotion\PromotionAction
        promotion_coupon:
            classes:
                model: App\Entity\Promotion\PromotionCoupon

sylius_review:
    resources:
        product:
            review:
                classes:
                    model: App\Entity\Product\ProductReview

sylius_shipping:
    resources:
        shipment:
            classes:
                model: App\Entity\Shipping\Shipment
        shipping_method:
            classes:
                model: App\Entity\Shipping\ShippingMethod
            translation:
                classes:
                    model: App\Entity\Shipping\ShippingMethodTranslation
        shipping_category:
            classes:
                model: App\Entity\Shipping\ShippingCategory

sylius_taxation:
    resources:
        tax_category:
            classes:
                model: App\Entity\Taxation\TaxCategory
        tax_rate:
            classes:
                model: App\Entity\Taxation\TaxRate

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
            translation:
                classes:
                    model: App\Entity\Taxonomy\TaxonTranslation
sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: App\Entity\User\AdminUser
        shop:
            user:
                classes:
                    model: App\Entity\User\ShopUser
        oauth:
            user:
                classes:
                    model: App\Entity\User\UserOAuth

sylius_shop:
    product_grid:
        include_all_descendants: true
    checkout_resolver:
        pattern: /checkout/.+
        route_map:
            cart:
                route: sylius_shop_checkout_address
            addressed:
                route: app_shop_checkout_select_shipping_and_payment
sylius_theme:
    sources:
        filesystem:
            scan_depth: 1
            directories:
                - "%kernel.project_dir%/themes"
winzou_state_machine:
    sylius_order_checkout:
        transitions:
            complete:
                from: [addressed]
                to: completed
        callbacks:
            after:
                app_select_shipping:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'select_shipping'", "'sylius_order_checkout'"]
                app_select_payment:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'select_payment'", "'sylius_order_checkout'"]

sylius_grid:
    templates:
        action: 
            active_toggle: 'App/Grid/Action/active_toggle.html.twig'
    grids:
        app_admin_pickup_point:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Shipping\PickupPoint
            fields:
                name:
                    type: string
                    sortable: ~
                    label: sylius.ui.name
                city:
                    type: string
                    sortable: ~
                    label: sylius.ui.city
                address:
                    type: string
                    label: sylius.ui.address
                active:
                    type: twig
                    label: sylius.ui.active
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                city:
                    type: string
                    label: sylius.ui.city
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:                                    
                    create:
                        type: create
                item:
                    active:
                        type: active_toggle
                        options:
                            link:
                                route: app_admin_pickup_point_active_toggle
                                parameters:
                                    pointId: resource.id
                    
        app_product_refund:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Product\ProductRefund
                    repository:
                        method: createQueryBuilderByProductId
                        arguments: ['!!int $productId']
            fields:
                code: 
                    type: string
                    label: sylius.ui.code
                discount:
                    type: string
                    label: app.ui.discount
                active:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                item:
                    update:
                        type: update
                        options:
                            link:
                                parameters:
                                    id: resource.id
                                    productId: $productId
                main:                                    
                    create:
                        type: create
                        options:
                            link:
                                parameters:
                                    productId: $productId
        app_admin_refund:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Order\Refund
            fields:
                order:
                    type: twig
                    label: sylius.ui.status
                    options:
                        template: 'App\Refund\Grid\order.html.twig'
                state:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    path: order.state
                    options:
                        template: "@SyliusUi/Grid/Field/state.html.twig"
                        vars:
                            labels: "@SyliusAdmin/Order/Label/State"
                bankAccount:
                    type: string
                    label: sylius.ui.bank_account
                issueDate:
                    type: datetime
                    label: sylius.ui.issue_date
            actions:
                item:
                    show:
                        type: show
sylius_resource:
    resources:
        app.pickup_point:
            classes: 
                model: App\Entity\Shipping\PickupPoint
                interface: App\Entity\Shipping\PickupPointInterface
                factory: App\PickupPoint\Factory\PickupPointFactory
                form: App\PickupPoint\Form\Type\PickupPointType
                controller: App\Controller\Admin\PickupPointController
        app.product_refund:
            classes:
                model: App\Entity\Product\ProductRefund
                factory: App\Factory\ProductRefundFactory
                form: App\Form\Type\Product\ProductRefundType
                interface: App\Entity\Product\ProductRefundInterface
                repository: App\Repository\ProductRefundRepository
                
        app.order_refund:
            classes:
                model: App\Entity\Order\Refund
                form: App\Form\Type\RefundType
                factory: App\Factory\RefundFactory
                repository: App\Repository\RefundRepository

odiseo_blog:
    resources:
        article:
            classes:
                model: App\Entity\Blog\Article
            translation:
                classes:
                    model: App\Entity\Blog\ArticleTranslation
