sylius_mailer:
    sender:
        name: Medorto Zakupy
        address: "zakupy@medorto.pl"
    emails:
        user_registration:
            sender:
                name: Medorto
                address: "zakupy@medorto.pl" # "medorto@medorto.pl"
        verification_token:
            sender:
                name: Medorto
                address: "zakupy@medorto.pl" # "medorto@medorto.pl"
        reset_password_token:
            sender:
                name: Medorto
                address: "zakupy@medorto.pl" # "medorto@medorto.pl"
        order_send_preparation:
            template: "Email/order_send_preparation.html.twig"
            sender:
                name: Medorto Zakupy
                address: "zakupy@medorto.pl"
                
