app_admin_refund:
    resource: |
        alias: app.order_refund
        section: admin
        templates: "@SyliusAdmin/Crud"
        except: ['show']
        grid: app_admin_refund
    type: sylius.resource

app_admin_order_refund_show:
    path: /order-refunds/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.order_refund:showAction
        _sylius:
            section: admin
            permission: true
            template: "App/Refund/Admin/show.html.twig"
